### ISSUE TITLE
1.19.X Compatbility?

### ISSUE THREAD

**Issue by Afrocntrik** [devs-immortal/Primeval#44]
Most mods are currently still on 1.19 and have 1.19 - 1.19.2 compat please allow the same for this mod otherwise this mod is amazing and keep up the great work!

**Comment by MBatt1** [comment]
What mod are you trying to use with Primeval? Because of how this mod is structured, any mods that add new content are going to be incompatible without custom recipes and other support. I have no plans to backport to 1.19 at the moment, especially this early in development, where most of the focus is going on new features. 
Sorry for the inconvenience.
